### ISSUE TITLE
  `Error: bash: command not found` when running on Windows 11 self-hosted runner.

### ISSUE THREAD

**Issue by Sermilion** [nickwph/firebase-app-distribution-action#5]
I was trying out this action on self-hosted runner, running on Windows 11 machine, and got this error. My setup looks like this:

```
      - name: Firebase App Distribution
        uses: nickwph/firebase-app-distribution-action@v1.2.1
        with:
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          credentials-file: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: app\build\outputs\apk\Internal\debug\app-debug.apk
```

The error is below. I have PowerShell 7 set and default and other actions required it. Might be this is not specific to this action, but I cant figure out how to fix it.
```
Run nickwph/firebase-app-distribution-action@v1.2.1
Run actions/cache@v3
Cache not found for input keys: firebase-tools
Run echo "GOOGLE_APPLICATION_CREDENTIALS=***
  echo "GOOGLE_APPLICATION_CREDENTIALS=***
    ***
    ***
    ***
    ***
    ***
    ***
    ***
    ***
    ***
    ***
    ***
  ***
  " >> $GITHUB_ENV
  Error: bash: command not found
```

UPDATE.

I installed Ubuntu on my Windows as subsystem and I get different error:

```
Run nickwph/firebase-app-distribution-action@v1.2.1
  with:
    credentials-file: ***
    file: app\build\outputs\apk\Internal\debug\app-debug.apk
    debug: false
    cache: true
    upgrade: true
  env:
    GRADLE_ACTION_ID: gradle/actions/setup-gradle
    JAVA_HOME: /home/sermilion/actions-runner/_work/_tool/Java_Adopt_jdk/17.0.11-9/x64
    JAVA_HOME_17_X64: /home/sermilion/actions-runner/_work/_tool/Java_Adopt_jdk/17.0.11-9/x64
    ANDROID_HOME: /home/sermilion/.android/sdk
    ANDROID_SDK_ROOT: /home/sermilion/.android/sdk
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    DEVELOCITY_INJECTION_INIT_SCRIPT_NAME: gradle-actions.inject-develocity.init.gradle
    DEVELOCITY_AUTO_INJECTION_CUSTOM_VALUE: gradle-actions
    DEVELOCITY_INJECTION_ENABLED: true
    DEVELOCITY_PLUGIN_VERSION: 3.17.5
    DEVELOCITY_CCUD_PLUGIN_VERSION: [2](https://github.com/***/actions/runs/9946717649/job/27477867508#step:10:2).0
    DEVELOCITY_TERMS_OF_USE_URL: https://gradle.com/terms-of-service
    DEVELOCITY_TERMS_OF_USE_AGREE: yes
    GITHUB_DEPENDENCY_GRAPH_ENABLED: false
Run actions/cache@v[3](https://github.com/***/actions/runs/9946717649/job/27477867508#step:10:3)
  
Cache not found for input keys: firebase-tools
Run echo "GOOGLE_APPLICATION_CREDENTIALS=***
Error: Unable to process file command 'env' successfully.
Error: Invalid format '  type: service_account,'
```
Looks like it has some issues reading my `CREDENTIAL_FILE_CONTENT` secred, which I got from service accounts section of google firebase. It is a value from json key generated there:
![image](https://github.com/user-attachments/assets/de9f9cec-2156-4098-bbc3-aaaf02172949)
